name: 'workflow-runs'
description: 'Summary of workflow runs for a given repository'
author: 'Satvik shukla'

branding:
  icon: 'heart'
  color: 'red'

inputs:
  github-repository:
    description: 'Name of github repository to list workflow runs for'
    required: false
    default: ''
  workflow-run-status:
    description: 'Status of workflow runs to filter'
    required: false
    default: ''
  workflow-run-created:
    description: 'Created time/date syntax of workflow runs to filter'
    required: false
    default: ''
  workflow-run-branch:
    description: 'Branch of workflow runs to filter'
    required: false
    default: ''
  workflow-run-actor:
    description: 'Actor of workflow runs to filter'
    required: false
    default: ''

outputs:
  runs-summary:
    description: 'Workflow runs output'
  runs-count:
    description: 'Workflow runs count'

runs:
  using: node20
  main: dist/index.js
