name: Version bump

on:
  workflow_dispatch:
    inputs:
      version_update_type:
        type: choice
        description: Version update type
        options:
          - patch
          - minor
          - major

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_PACKAGE_PAT }}
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Create commits
        run: |
          git config user.name 'Satvik'
          git config user.email 'satvik-s@users.noreply.github.com'
          git checkout -b sshukla/temp-version-bump
          npm version ${{ inputs.version_update_type }}
      - name: Get release tag
        id: get-release-tag
        shell: bash
        run:
          echo "release-tag=v$(jq -r .version package.json)" >> $GITHUB_OUTPUT
      - name: Push changes
        run: |
          git checkout -b sshukla/version-bump-$VERSION
          git push -u origin HEAD
          gh pr create --title "chore: update version to $VERSION" --body "update to version $VERSION" --base main --assignee satvik-s
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_PACKAGE_PAT }}
          VERSION: ${{ steps.get-release-tag.outputs.release-tag }}
